services:
  database:
    image: postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
  bot:
    build: .
    tty: true
    command: python launcher.py
    volumes:
      - .:/bot

volumes:
  postgresql:
